name : Install Mongo DB on Ubunutu 16.04
desc : The recipe installs the mongo db on Ubunutu 16.04  
logo_url: https://raw.githubusercontent.com/tanmally/mongo-ubuntu-16/master/logo/mongo.jpg
tags:
    - mongo db
    - install
    - latest
    - Ubunutu 16.04
 
task:

  - name: Install mongo db server
    cmd:
        - export DEBIAN_FRONTEND=noninteractive
        - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
        - echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list
        - apt-get update  
        - apt-get install -y mongodb-org
        - systemctl start mongod
        - systemctl enable mongod
        - echo Done installing mongo db server       
          
  - name: Copy setup script file 
    copy: 
         src_file: script/db_config.sh
         target_dir: /opt/mongo/script/
         target_file_name : db_config.sh
         create_target_dir_if_missing : true 

  - name: Run mongo db auth setup script
    cmd:
        - export DEBIAN_FRONTEND=noninteractive
        - chmod +x /opt/mongo/script/db_config.sh
        - /opt/mongo/script/db_config.sh
        - rm -f /opt/mongo/script/db_config.sh
        - echo Done running mongo db auth setup
    vars:
        - MONGODB_USERNAME
        - MONGODB_PASSWORD
        
  - name: Copy mongod conf file 
    copy: 
         src_file: conf/mongod.conf
         target_dir: /etc/
         target_file_name : mongod.conf
         create_target_dir_if_missing : true 
     vars:
        - MONGODB_PORT
        - MONGODB_BIND_IP

  
